# Generated by Django 2.0.2 on 2018-03-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0002_auto_20180303_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-uploaded_at',)},
        ),
    ]
